{% set version = "2.2.1" %}

package:
    name: jsmin
    version: {{ version }}

source:
    fn: jsmin-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/j/jsmin/jsmin-{{ version }}.tar.gz
    sha256: df7fe41d6de1df42cb5dcfdefe1d7285b584ec6f2a714f6c05f6e6dbacff7f71

build:
    noarch: python
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - jsmin

about:
    home: https://github.com/tikitu/jsmin
    license: MIT
    summary: 'JavaScript minifier'

extra:
    recipe-maintainers:
        - daf
