{% set version = "2.2.2" %}

package:
    name: jsmin
    version: {{ version }}

source:
    fn: jsmin-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/j/jsmin/jsmin-{{ version }}.tar.gz
    sha256: b6df99b2cd1c75d9d342e4335b535789b8da9107ec748212706ef7bbe5c2553b

build:
    noarch: python
    number: 1001
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    host:
        - python
        - pip
    run:
        - python

test:
    imports:
        - jsmin

about:
    home: https://github.com/tikitu/jsmin
    license: MIT
    summary: 'JavaScript minifier'

extra:
    recipe-maintainers:
        - daf
